config/routes.rb
Poly::Application.routes.draw do

  resources :infoproductos


  resources :informaciones

  match "/quienes-somos" => "informaciones#index", :as => 'quienes_somos', :via => :get

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do

    resources :categorias do
      resources :subcategorias
    end

    resources :subcategorias do
      resources :tipos
    end

    resources :tipos do
      resources :productos
    end

    resources :contactos

    devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

    match "/quienes-somos" => "quienes_somos#index", :as => 'quienes_somos', :via => :get

    resources :diapositivas

    get 'inicio/editar_texto_de_inicio'

    put 'inicio/update_texto_de_inicio'

    root to: 'inicio#index'

    match "/cpanel" => redirect("http://cpanel.manufacturaspoly.com:2082"), :as => :cpanel

  end

end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
    @diapositivas = Diapositiva.all
    @texto_de_inicio = TextoDeInicio.first
  end
  def editar_texto_de_inicio
    @texto_de_inicio = TextoDeInicio.first
  end

  def update_texto_de_inicio
    @texto_de_inicio = TextoDeInicio.first
    @texto_de_inicio.update_attributes(params[:texto_de_inicio])
    if @texto_de_inicio.save
      redirect_to action: 'index'
    end
  end
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/inicio/_bootstrap_slider.html.haml
#main-carrusel.carousel-projects.slide

  %ol.carousel-indicators
    - @diapositivas.each_with_index do |diapositiva, index|
      - if index == 0
        %li{:"data-target" => "#main-carrusel", :"data-slide-to" => index.to_s, :class => 'active span2 first-thumb'}
          = image_tag diapositiva.imagen_url(:thumb)
      - else
        %li{:"data-target" => "#main-carrusel", :"data-slide-to" => index.to_s, :class => 'span2'}
          = image_tag diapositiva.imagen_url(:thumb)

  <!-- Carousel items -->
  .carousel-inner
    - @diapositivas.each_with_index do |diapositiva, index|
      - if index == 0
        .item.active
          = render 'slide', :diapositiva => diapositiva
      - else
        .item
          = render 'slide', :diapositiva => diapositiva

  <!-- Carousel nav -->
  .control-wrapper
    = link_to raw('&lsaquo;'), '#main-carrusel', :"data-slide" => 'prev', :class => 'carousel-control left'
    = link_to raw('&rsaquo;'), '#main-carrusel', :"data-slide" => 'next', :class => 'carousel-control right'

app/views/inicio/_slide.html.haml
= image_tag diapositiva.imagen_url(:full)
.carousel-caption
  %h3
    = diapositiva.titulo
  %p.descripcion
    = diapositiva.descripcion
  - if diapositiva.link?
    = link_to 'Ver más', diapositiva.link, class: 'btn btn-default'

app/views/inicio/editar_texto_de_inicio.html.haml
= form_for @texto_de_inicio, url: inicio_update_texto_de_inicio_path, method: :put, html: { class: 'form-horizontal', role: 'form' } do |f|
  - if @texto_de_inicio.errors.any?
    #error_explanation
      %h2= "#{pluralize(@texto_de_inicio.errors.count, "error")}"
      %ul
        - @texto_de_inicio.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    .col-sm-10
      %h1.editar
        Editar Texto

  .form-group
    = f.label :nosotros
    .col-sm-10
      = f.text_area :nosotros
  .form-group
    = f.label :productos
    .col-sm-10
      = f.text_area :productos
  .form-group
    = f.label :contactos
    .col-sm-10
      = f.text_area :contactos
  .form-group
    = f.label :titulo
    .col-sm-10
      = f.text_field :titulo
  .form-group
    = f.label :contenido
    .col-sm-10
      = f.text_area :contenido
  .actions
    = f.submit 'Guardar', class: 'btn btn-default'

app/views/inicio/index.html.haml
.row
  .span12
    = render 'bootstrap_slider.html'
.row
  .span9
    - if @texto_de_inicio
      %ul.thumbnails.custom-thumbnails
        %li.span3
          = link_to image_tag('img-home-nosotros.jpg'), quienes_somos_path, class: 'thumbnail'
          %h3.title Nosotros
          %p.text-center= raw(@texto_de_inicio.nosotros)

        %li.span3
          = link_to image_tag('img-home-productos.jpg'), categorias_path, class: 'thumbnail'
          %h3.title Productos
          %p.text-center= raw(@texto_de_inicio.productos)

        %li.span3
          = link_to image_tag('img-home-contacto.jpg'), new_contacto_path, class: 'thumbnail'
          %h3.title Contacto
          %p.text-center= raw(@texto_de_inicio.contactos)

      %h4.media-heading
        = @texto_de_inicio.titulo
      %p
        = @texto_de_inicio.contenido
    - if current_admin
      = link_to 'Editar Contenidos', inicio_editar_texto_de_inicio_path, class: 'btn btn-default'
  .span3
    .sidebar-nav
      %h3.title Actualizaciones
      = render '/shared/facebook_like_box'
      = link_to image_tag('btn-sigue.jpg', class: 'no-resp'), '/'