config/routes.rb
Poly::Application.routes.draw do

  resources :infoproductos


  resources :informaciones

  match "/quienes-somos" => "informaciones#index", :as => 'quienes_somos', :via => :get

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do

    resources :categorias do
      resources :subcategorias
    end

    resources :subcategorias do
      resources :tipos
    end

    resources :tipos do
      resources :productos
    end

    resources :contactos

    devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

    match "/quienes-somos" => "quienes_somos#index", :as => 'quienes_somos', :via => :get

    resources :diapositivas

    get 'inicio/editar_texto_de_inicio'

    put 'inicio/update_texto_de_inicio'

    root to: 'inicio#index'

    match "/cpanel" => redirect("http://cpanel.manufacturaspoly.com:2082"), :as => :cpanel

  end

end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  attr_accessible :descripcion, :imagen, :nombre

  belongs_to :categoria
  has_many :tipos, :dependent => :destroy

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/controllers/subcategorias_controller.rb
class SubcategoriasController < InheritedResources::Base

  belongs_to :categoria

  def create
    create! { categoria_subcategorias_path(@categoria)}
  end

  def update
    update! { categoria_subcategorias_path(@categoria)}
  end

end

app/helpers/subcategorias_helper.rb
module SubcategoriasHelper
end

app/views/subcategorias/_form.html.haml
= form_for [@subcategoria.categoria, @subcategoria], html: {multipart: true} do |f|
  - if @subcategoria.errors.any?
    #error_explanation
      %h2= "#{pluralize(@subcategoria.errors.count, "error")} en subcategoria"
      %ul
        - @subcategoria.errors.full_messages.each do |msg|
          %li= msg
  .row
    .span3
      .field
        = f.label :nombre
        = f.text_field :nombre
      .field
        = f.label :descripcion
        = f.text_area :descripcion
      .field
        = f.label :imagen
        = f.file_field :imagen
      .actions
        = f.submit 'Guardar', class: 'btn btn-default'

app/views/subcategorias/edit.html.haml
= page_title(raw('Editar <b>subcategoria</b>'))

.row
  .span12

    = link_to 'Cancelar', '', class: 'btn btn-default btn-left back-js'
    = render 'form'

app/views/subcategorias/index.html.haml
- if current_admin
  .admin-links-top
    = link_to 'Nuevo  Subcategoria', new_categoria_subcategoria_path(@categoria), class: 'btn btn-default'

= page_title('Productos | ' + @categoria.nombre)
= page_encabezado(@categoria.nombre, @categoria.icono_url(:thumb))
%p= @categoria.descripcion
= page_encabezado_end

- @subcategorias.each_slice(2) do |subcategoria|
  .row
    - subcategoria.each do |subcategoria|
      %div{class: cycle('span5', 'span5 offset1')}
        .img-wrapper
          = image_tag(subcategoria.imagen_url(:span5))
          = link_to 'Ver más', subcategoria_tipos_path(subcategoria), class: 'btn btn-view-more'

        %h3.title-block.colored.well.subcat
          = link_to subcategoria.nombre, subcategoria_tipos_path(subcategoria)
        .well
          = paragraph(subcategoria.descripcion)

          =# link_to image_tag(subcategoria.icono), '', class: 'btn-view-more'

          - if current_admin
            .actions
              = link_to 'Editar', edit_categoria_subcategoria_path(@categoria, subcategoria), class: 'btn btn-default'
              = link_to 'Eliminar', categoria_subcategoria_path(@categoria, subcategoria), :method => :delete, :data => { :confirm => '¿Estás Seguro?' }, class: 'btn btn-default'

app/views/subcategorias/new.html.haml
= page_title('Nuevo subcategoria')

.row
  .span12

    = link_to 'Cancelar', '', class: 'btn btn-default btn-left back-js'
    = render 'form'

app/views/subcategorias/show.html.haml
= page_title('subcategoria')

.row
  .span12

    = link_to 'Atrás', '', class: 'btn btn-default btn-left back-js'

    - if current_admin
      = link_to 'Editar', edit_subcategoria_path(@subcategoria), class: 'btn btn-default'
.row
  .span6
    %b Nombre:
    = @subcategoria.nombre
    %b Descripcion:
    = @subcategoria.descripcion
    %b Imagen:
    = @subcategoria.imagen
    %b Icono:
    = @subcategoria.icono