config/routes.rb
Poly::Application.routes.draw do

  resources :infoproductos


  resources :informaciones

  match "/quienes-somos" => "informaciones#index", :as => 'quienes_somos', :via => :get

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do

    resources :categorias do
      resources :subcategorias
    end

    resources :subcategorias do
      resources :tipos
    end

    resources :tipos do
      resources :productos
    end

    resources :contactos

    devise_for :admins, :path => "cms", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }

    match "/quienes-somos" => "quienes_somos#index", :as => 'quienes_somos', :via => :get

    resources :diapositivas

    get 'inicio/editar_texto_de_inicio'

    put 'inicio/update_texto_de_inicio'

    root to: 'inicio#index'

    match "/cpanel" => redirect("http://cpanel.manufacturaspoly.com:2082"), :as => :cpanel

  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  attr_accessible :descripcion, :icono, :imagen, :nombre

  has_many :subcategorias, :dependent => :destroy

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :icono, IconoUploader
  mount_uploader :imagen, ImagenUploader
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  #include MailForm::Delivery
  attr_accessible :apellido, :direccion, :email, :empresa, :mensaje, :nombre, :telefono

  #attribute :nombre,    :validate => true
  #attribute :apellido,  :validate => true
  #attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  #attribute :mensaje
  #attribute :direccion
  #attribute :empresa
  #attribute :telefono
  #attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  #def headers
  #  {
  #    :subject => "Mensaje desde la web",
  #    :to => "paul@kosmyka.com",
  #    :from => %("#{nombre} #{apellido}" <#{email}>)
  #  }
  #end

end

app/models/diapositiva.rb
class Diapositiva < ActiveRecord::Base
  attr_accessible :descripcion, :imagen, :slug, :titulo

  extend FriendlyId
  friendly_id :titulo, use: :slugged

  mount_uploader :imagen, DiapositivaUploader
end

app/models/infoproducto.rb
class Infoproducto < ActiveRecord::Base
  attr_accessible :subtitulo, :titulo
end

app/models/informacion.rb
class Informacion < ActiveRecord::Base
  attr_accessible :foto1, :foto2, :mision, :resenia, :vision

  mount_uploader :foto1, FotoUploader
  mount_uploader :foto2, FotoUploader
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :imagen, :nombre

  belongs_to :tipo

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/models/subcategoria.rb
class Subcategoria < ActiveRecord::Base
  attr_accessible :descripcion, :imagen, :nombre

  belongs_to :categoria
  has_many :tipos, :dependent => :destroy

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/models/texto_de_inicio.rb
class TextoDeInicio < ActiveRecord::Base
  attr_accessible :contactos, :contenido, :nosotros, :productos, :titulo
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  attr_accessible :descripcion, :imagen, :nombre

  belongs_to :subcategoria
  has_many :productos, :dependent => :destroy

  extend FriendlyId
  friendly_id :nombre, use: :slugged

  mount_uploader :imagen, ImagenUploader
end

app/controllers/tipos_controller.rb
class TiposController < InheritedResources::Base

  belongs_to :subcategoria

  def create
    create! { subcategoria_tipos_path(@subcategoria)}
  end

  def update
    update! { subcategoria_tipos_path(@subcategoria)}
  end

end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper





  # PARAGRAPH
  def paragraph(text)
    "#{sanitize(simple_format(text), :tags => %w(p i br b))}".html_safe
  end

  def paragraph_truncate(text, length)
    "#{sanitize(simple_format(truncate(text, :length => length)), :tags => %w(p i br b))}".html_safe
  end
  def page_title(titulo)
    "#{'<div class="row page-title-wrapper">
        <div class="span12">
          <h1>' + titulo + '</h1>
        </div></div>'}".html_safe
  end



  def holder_tag(size, text='', theme=nil, html_options={})
      size = "#{size}x#{size}" unless size =~ /\A\d+%?x\d+\z/
      text = text.to_s.empty? ? size : text
      options = {:src => '', :data => {:src => "holder.js/#{size}/text:#{text}/#{theme}"}}
      options = options.merge(html_options)

      tag :img, options
    end




  def page_encabezado(subtitulo, imagen)

   # - if imagen == "#{holder_tag '270x185/industrial'}"
   #   tag_image = '<img src="' + imagen + '" />'
   # - else
   #   tag_image = imagen


    "#{'<div class="row page-encabezado">
          <div class="span12">
            <div class="media">
              <div class="pull-left">
                <img src="' + imagen + '" />
              </div>
              <div class="media-body">
                <div class="well">
                  <h2 class="media-heading">' + subtitulo +'</h2>'}".html_safe


  end

  def page_encabezado_end
    "#{'</div></div></div></div></div>'}".html_safe
  end




  # ADMIN
  def admin_links(size_link, edit_text, edit_link, delete_text, delete_link)
    if current_admin
      "#{'<div class="btn-group">
      <a class="btn btn-primary ' + size_link +'" href="' + edit_link + '"><i class="icon-pencil icon-white"></i>' + edit_text + '</a>
      <a class="btn btn-primary dropdown-toggle ' + size_link +'" data-toggle="dropdown" href="#"><span class="caret"></span></a>
      <ul class="dropdown-menu">
      <li><a href="' + edit_link + '"><i class="icon-pencil"></i> ' + edit_text +'</a></li>
      <li class="link-destroy"><a href="' + delete_link + '" rel="nofollow" data-method="delete" data-confirm="¿Estás seguro?"
><i class="icon-trash"></i> ' + delete_text + '</a></li>
      </ul>
      </div>'}".html_safe
    end


  end

  def admin_links_extra(size_link, edit_text, edit_link, delete_text, delete_link, create_text, create_link)
    if current_admin
      "#{'<div class="btn-group">
      <a class="btn btn-primary ' + size_link +'" href="' + edit_link + '"><i class="icon-pencil icon-white"></i>' + edit_text + '</a>
      <a class="btn btn-primary dropdown-toggle ' + size_link +'" data-toggle="dropdown" href="#"><span class="caret"></span></a>
      <ul class="dropdown-menu">
      <li><a href="' + edit_link + '"><i class="icon-pencil"></i> ' + edit_text +'</a></li>
      <li><a href="' + delete_link + '" rel="nofollow" data-method="delete" data-confirm="¿Estás seguro?"><i class="icon-trash"></i> ' + delete_text + '</a></li>
      <li class="divider"></li>
      <li><a href="' + create_link + '"><i class="i"></i> ' + create_text + '</a></li>
      </ul>
      </div>'}".html_safe
    end
  end




end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/diapositivas_helper.rb
module DiapositivasHelper
end

app/helpers/infoproductos_helper.rb
module InfoproductosHelper
end

app/helpers/informaciones_helper.rb
module InformacionesHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/layouts/_menu.html.haml
.separate-row.clearfix.menu-bg
  %ul#main-nav.nav.pull-left
    %li.first
      = link_to_unless_current image_tag('ico-home-off.png', class: 'off') + image_tag('ico-home-on.png', class: 'on') + ' Inicio', root_path do
        = image_tag('ico-home-on.png') + raw('<span>Inicio</span>')

    %li
      = link_to_unless_current 'Nosotros', quienes_somos_path do
        %span
          Nosotros
    %li
      = link_to_unless_current 'Productos', categorias_path do
        %span
          Productos
    - if current_admin
      %li
        = link_to_unless_current 'Banners', diapositivas_path do
          %span
            Banners
      %li
        = link_to_unless_current 'Mensajes', contactos_path do
          %span
            Mensajes
      %li.last
        = link_to_unless_current 'Cerrar Sesión', destroy_admin_session_path, method: :delete do
          %span
            Cerrar Sesión
    - else
      %li.last
        = link_to_unless_current 'Contacto', new_contacto_path do
          %span
            Contacto

app/views/layouts/_pre_header.html.haml
#header-top.row
  #header-top-inner.span12
    .well.well-small
      .encabezado-links.pull-right
        = link_to 'Login', '', class: 'link last'

app/views/layouts/application.html.haml
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js ie6 lt-ie9 lt-ie8 lt-ie7 lt-ie10 ie" lang="en">
/[if IE 7] <html class="no-js ie7 lt-ie9 lt-ie8 lt-ie10 ie" lang="en">
/[if IE 8] <html class="no-js ie8 lt-ie9 lt-ie10" lang="en">
/[if IE 9] <html class="no-js ie9 lt-ie10" lang="en">
/ Consider adding a manifest.appcache: h5bp.com/d/Offline
/ [if gt IE 9]><!
%html.no-js.gt-ie9.non-ie{:lang => "en"}
  / <![endif]
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Poly"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag '/ico/poly-icon-144.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag '/ico/poly-icon-114.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag '/ico/poly-icon-72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag '/ico/poly-icon-57.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag '/ico/favicon.png', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body{id: bodyid, class: bodyclass}
    %header#main-header
      .container
        = render 'layouts/pre_header'
        .row
          .span2
            %h1
              = link_to image_tag('logo.png', alt: 'Poly Manufacturas'), '/', class: 'brand'
          .span10
            %nav.navbar
              .navbar-inner
                .container
                  %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
                    %span.icon-bar
                    %span.icon-bar
                    %span.icon-bar
                  .nav-collapse.collapse
                    = render 'shared/social_links'
                    = render 'layouts/menu'

    %section#main-content.container
      = yield


      %footer#main-footer
        .well
          %p &copy; Copyright | Manufacturas Poly S.A.C. Todos los derechos reservados
          = link_to 'http://www.mpsac.com.pe/webmail' do
            = image_tag image_path('logo-poly-blanco.png')